# .DROP()

In [1]:
import pandas as pd
# reads csv file
df = pd.read_csv('players_20.csv')
# set index
df.set_index('short_name', inplace=True)
# select column
df = df[['long_name', 'age', 'dob', 'height_cm', 'weight_kg', 'nationality', 'club']]

In [4]:
df.drop(['L. Messi'],axis=0,inplace=True)

In [6]:
df.drop(['club'],axis=1)

,long_name,age,dob,height_cm,weight_kg,nationality
short_name,,,,,,
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium
...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR
Zhang Wei,张威,19,2000-05-16,186,75,China PR
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR

# .sample()

In [7]:
df['nationality'].sample(5)

short_name
Florentino      Portugal
J. Wurtz         Germany
M. Shved         Ukraine
C. Stockton      England
Danilo Silva      Brazil
Name: nationality, dtype: object

In [15]:
df['nationality'].sample(5, random_state=99)
#99- least change in sample all the way to 1

short_name
Alberto Soro        Spain
S. Ingason        Iceland
M. Gargiulo         Italy
I. Khalili      Palestine
C. Woodrow        England
Name: nationality, dtype: object

In [16]:
df.shape

(18277, 7)

In [19]:
df['nationality'].sample(frac=.1, random_state=99).shape
#99- least change in sample all the way to 1            #FRAC=.1 MEANS 10% OF DF TO GIVE AS SAMPLE

(1828,)

# REPLACE 2X

In [ ]:
# upsample: increase the sampling rate -> frac>1  (Note: replace parameter has to be True for frac parameter > 1)
df.sample(frac=2, replace=True, random_state=99)

# QUERY

In [21]:
df.query('not(age>34)')

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

In [22]:
df.dtypes

long_name      object
age             int64
dob            object
height_cm       int64
weight_kg       int64
nationality    object
club           object
dtype: object

In [28]:
# conver "dob" column to datetime type
df['dob'] = df['dob'].astype('datetime64[ns]')
# query
df.query("dob.dt.year > 1990")

# exercise: write the equivalent boolean slicing
df[df['dob'].dt.year>1990]

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
K. De Bruyne,Kevin De Bruyne,28,1991-06-28,181,70,Belgium,Manchester City
M. ter Stegen,Marc-André ter Stegen,27,1992-04-30,187,85,Germany,FC Barcelona
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC